lib/libopenswan/constants.c: fix build on uclibc-ng
Use ns_t_tsig - 1 instead of ns_t_tkey which is not defined in uclibc-ng
resulting in the following build failure:

openswan-2.6.52.2/lib/libopenswan/constants.c:1432:31: error: ‘ns_t_tkey’ undeclared here (not in a function)
 enum_names rr_qtype_names = { ns_t_tkey, ns_t_any
                               ^

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>